### PR TITLE
Initial bindings and setup

### PR DESCRIPTION
**Pull request by faern**
Let's get started on the road towards the Linux firewall. First step is to have a library for talking netlink to the netfilter/nf-tables kernel module.

There are a few existing netlink libraries in Rust, so why write my own? First of all, which features do I need?:
* Netlink socket - I must be able to send and receive netlink packets to and from the kernel.
* Parsing of response packets.

The best alternatives I found for netlink communication were [crslmnl](https://crates.io/crates/crslmnl) and [neli](https://crates.io/crates/neli).
The reason I skipped `neli` was because it only supports the socket part, not parsing of the responses. The plus side of this crate is that it's pure Rust and has less C dependencies. In some future where it's more complete we might be able to switch over to this.
The reason I skipped `crslmnl` was that it did not really support part of my use case, or it was hard to use in that way. Since I started they merged my PR fixing a few things, so it's a bit better now. But they still have quite a lot of design choices that I feel are not optimal. Plus quite heavy dependencies.

This repository will contain two crates, `mnl-sys` and `mnl`. The former is just pure auto-generated bindings to the C interface and has no logic except very few things that bindgen failed to generate. The latter will be filled in with safe abstractions. Since we only need a tiny subset of `libmnl` I will only implement that part for now.

On top of this I will later introduce the `nftnl` crate, which is a wrapper on top of 
[`libnftnl`](https://www.netfilter.org/projects/libnftnl/index.html) (a userspace library providing a low-level netlink programming interface (API) to the in-kernel nf_tables subsystem)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mnl-rs/1)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 23 at r1](https://reviewable.io:443/reviews/mullvad/mnl-rs/1#-L6HEYYvR4aNUh7Efek5:-L6HEYYvR4aNUh7Efek6:b52g8ty) ([raw file](https://github.com/mullvad/mnl-rs/blob/4c42a81c9bbd15f1fadd61e2d9acdd9bd8e3fa13/.travis.yml#L23)):*
> ```YAML
>   - cargo build --verbose --no-default-features
>   - cargo test --verbose --no-default-features
>   - cd ../
> ```

The `--no-default-features` flag does not work in a workspace. So to make it effective I had to cd into the "top" crate and run tests+builds there.

---

*[mnl-sys/build.rs, line 6 at r1](https://reviewable.io:443/reviews/mullvad/mnl-rs/1#-L6HF9Bjuhf2gizBbxso:-L6HF9Bjuhf2gizBbxsp:b-ogm439) ([raw file](https://github.com/mullvad/mnl-rs/blob/4c42a81c9bbd15f1fadd61e2d9acdd9bd8e3fa13/mnl-sys/build.rs#L6)):*
> ```Rust
> const MIN_VERSION: &str = "1.0.4";
> #[cfg(not(feature = "mnl-1-0-4"))]
> const MIN_VERSION: &str = "1.0.3";
> ```

The reason I take the extra step of adding this feature etc is that Travis runs Ubuntu 14.04 which only has `libmnl 1.0.3`, so I have to make it work on that version, but I also want to support the latest library release.

But this solution should work quite smooth I think. For every new `libmnl` release we just add a new feature flag, flag the new methods and make the latest the default that can be opt out of.

---

*[mnl-sys/src/bindings.rs, line 19 at r1](https://reviewable.io:443/reviews/mullvad/mnl-rs/1#-L6HEnvODlC4rZZ4s9HQ:-L6HEnvODlC4rZZ4s9HR:b-wbdb7) ([raw file](https://github.com/mullvad/mnl-rs/blob/4c42a81c9bbd15f1fadd61e2d9acdd9bd8e3fa13/mnl-sys/src/bindings.rs#L19)):*
> ```Rust
> }
> extern "C" {
>     #[cfg(feature = "mnl-1-0-4")]
> ```

I added these feature gates myself since I can't get bindgen to correctly insert them. The difference between `1.0.3` and `1.0.4` is only these two functions.

---

*[mnl-sys/src/lib.rs, line 24 at r1](https://reviewable.io:443/reviews/mullvad/mnl-rs/1#-L6HEzAW80zjtInrlps5:-L6HEzAXXzVbj84aySw9:b-hznwnu) ([raw file](https://github.com/mullvad/mnl-rs/blob/4c42a81c9bbd15f1fadd61e2d9acdd9bd8e3fa13/mnl-sys/src/lib.rs#L24)):*
> ```Rust
> 
> #[allow(non_snake_case)]
> pub fn MNL_SOCKET_BUFFER_SIZE() -> libc::c_long {
> ```

This is defined as a C style macro in `libmnl`. Bindgen can't pick those up so I wrote the definition manually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mnl-rs/1)*

**Comment by faern** [comment]
Review status: 0 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[mnl-sys/Cargo.toml, line 19 at r1](https://reviewable.io:443/reviews/mullvad/mnl-rs/1#-L6HGYLyIKr90vVApi1a:-L6HGYLzW7v1yZroafX3:b-mkx3nt) ([raw file](https://github.com/mullvad/mnl-rs/blob/4c42a81c9bbd15f1fadd61e2d9acdd9bd8e3fa13/mnl-sys/Cargo.toml#L19)):*
> ```TOML
> 
> [dependencies]
> libc = { version = "0.2", git = "https://github.com/faern/libc" }
> ```

At the moment this points to my fork. I got everything I need merged upstream, but it has not been release yet. As soon as the next version of `libc` comes out we can depend directly on the one on crates.io :ok_hand: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mnl-rs/1)*

**Comment by mvd-ows** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.travis.yml, line 23 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1#-L6HEYYvR4aNUh7Efek5:-L6LnoR45-dBkZt8Lc89:b70lx23) ([raw file](https://github.com/mullvad/mnl-rs/blob/4c42a81c9bbd15f1fadd61e2d9acdd9bd8e3fa13/.travis.yml#L23)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The `--no-default-features` flag does not work in a workspace. So to make it effective I had to cd into the "top" crate and run tests+builds there.
</blockquote></details>

Maybe that issue can shed some light on the flag and why it does not work for deps?

https://github.com/rust-lang/cargo/issues/1886

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[mnl-sys/build.rs, line 6 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1#-L6HF9Bjuhf2gizBbxso:-L6LoqN4EELiwsd6CClF:byvp75) ([raw file](https://github.com/mullvad/mnl-rs/blob/4c42a81c9bbd15f1fadd61e2d9acdd9bd8e3fa13/mnl-sys/build.rs#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The reason I take the extra step of adding this feature etc is that Travis runs Ubuntu 14.04 which only has `libmnl 1.0.3`, so I have to make it work on that version, but I also want to support the latest library release.

But this solution should work quite smooth I think. For every new `libmnl` release we just add a new feature flag, flag the new methods and make the latest the default that can be opt out of.
</blockquote></details>

If the slice of features from 1.0.3 satisfies your needs then maybe there is no point to run for 1.0.4. Just a thought, since this is a work in progress, if you don't have newer features used then maybe there is no need to complicate.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
Reviewed 4 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/1#-:-L6LpzKr2n9uNkLrTyhG:bnfp4nl)*

**Pull request merged**
