### PR TITLE
Cleanup sys crate

### PR DESCRIPTION
**Pull request by faern**
I have advanced a lot in the Linux firewall bindings. So it's time to start iterate this in PRs. First comes the netlink library. This per se has nothing with the firewall to do, it's just for communicating over netlink.

This PR cleans up the `mnl-sys` crate a bit. Mostly removes noise in the bindgen generated bindings. But see each commit and its message for a better description of what has happened.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mnl-rs/3)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[mnl-sys/Cargo.toml, line 15 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LARvsfU0F1XYbmiIQZd:-LARvsfU0F1XYbmiIQZe:b-cwwypx) ([raw file](https://github.com/mullvad/mnl-rs/blob/9800cd92e2d07a7ca61617377bbb8a924cf7a9e0/mnl-sys/Cargo.toml#L15)):*
> ```TOML
> 
> [features]
> default = ["mnl-1-0-4"]
> ```

As we learned while discussing another PR features are a bit special since they are opt-in but can't be forced to be disabled. If a dependency tree depends on the same crate twice but with different setup of features then it will be compiled only once for that build but with the union of the activated features. Thus one should activate as little as possible by default and let the depending crates only pull in what they need.

---

*[mnl-sys/src/lib.rs, line 32 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LARwHbd9-SfB8kT9Y9W:-LARwHbfCiF5pDVt7Q82:bftgwvd) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/lib.rs#L32)):*
> ```Rust
> #[allow(non_snake_case)]
> pub fn MNL_ALIGN(len: i32) -> i32 {
>     ((len) + MNL_ALIGNTO - 1) & !(MNL_ALIGNTO - 1)
> ```

I never use this anywhere. Mostly wanted to add it for completeness.
Can sadly not be used in a constant expression. Could be fixed by making it a macro, but I don't want to spend too much on this since it's not used yet.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pronebird** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pronebird** [comment]
Reviewed 1 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pinkisemils** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-:-LAS9txe78cG5Rm0oIu3:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pronebird** [comment]
Reviewed 4 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[mnl-sys/src/bindings.rs, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASAyKHBhEO1Mm6Jg0E:-LASAyKHBhEO1Mm6Jg0F:b6mkzka) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/bindings.rs#L1)):*
> ```Rust
> use core::option::Option;
> ```

Are these now manually produced bindings?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pronebird** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mnl-sys/src/bindings.rs, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASAyKHBhEO1Mm6Jg0E:-LASCycq3CKttSyB8DRS:b-42rdlr) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/bindings.rs#L1)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Are these now manually produced bindings?
</blockquote></details>

They actually were even before due to cfg(feature) guard.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-:-LASDcd43wc9bPx3NIa1:bnfp4nl)*

**Comment by jvff** [comment]
Reviewed 7 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[mnl-sys/src/bindings.rs, line 56 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASTmA4BEpnBdiv2VzB:-LASTmA4BEpnBdiv2VzC:b-pbaadn) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/bindings.rs#L56)):*
> ```Rust
>     pub fn mnl_socket_get_portid(nl: *const mnl_socket) -> c_uint;
> 
>     pub fn mnl_socket_sendto(nl: *const mnl_socket, req: *const c_void, siz: usize) -> isize;
> ```

Wouldn't it be better to use `libc::size_t` and `libc::ssize_t` instead of `usize` and `isize` for consistency?

---

*[mnl-sys/src/lib.rs, line 32 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASR62xCO-sHK3CPsPj:-LASR62xCO-sHK3CPsPk:b-xm6ew0) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/lib.rs#L32)):*
> ```Rust
> #[allow(non_snake_case)]
> pub fn MNL_ALIGN(len: i32) -> i32 {
>     ((len) + MNL_ALIGNTO - 1) & !(MNL_ALIGNTO - 1)
> ```

This appears to be a specialized version of:

```
let prepared = original + alignment - 1;
let aligned = prepared - prepared % alignment;
```

However, it requires the `MNL_ALIGNTO` to always be a power of two. It is now (4), but maybe it's a good idea to avoid this requirement in case the value changes in the future? Or maybe just change `MNL_ALIGNTO` to be `1 << 2`,  so its clearer?

---

*[mnl/src/callback.rs, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASQIXW0pD4hClo6vjR:-LASQIXW0pD4hClo6vjS:b-h1eqtv) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl/src/callback.rs#L1)):*
> ```Rust
> use mnl_sys::{self, c_int, c_void, nlmsghdr};
> ```

I don't understand why `nlmsghdr` is required. `c_int` appears to be unused as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mnl-sys/src/bindings.rs, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASAyKHBhEO1Mm6Jg0E:-LASWwif6cbW55Ty0nmq:b-sqajbc) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/bindings.rs#L1)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

They actually were even before due to cfg(feature) guard.
</blockquote></details>

They are initially generated by bindgen. But then I have polished it manually (the things I change in this PR) to make it easier to read and better in many ways that bindgen can't or is hard to configure to do.

---

*[mnl-sys/src/bindings.rs, line 56 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASTmA4BEpnBdiv2VzB:-LASX7-OBl-RcmvsgPAW:bepshvw) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/bindings.rs#L56)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Wouldn't it be better to use `libc::size_t` and `libc::ssize_t` instead of `usize` and `isize` for consistency?
</blockquote></details>

Those types were generated by bindgen. I have not changed any types as generated by bindgen. I personally don't feel that it's very important since they are just typedefs and are guaranteed to be the same size anyway?

---

*[mnl-sys/src/lib.rs, line 32 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASR62xCO-sHK3CPsPj:-LASXRLS7A2HWlzj2zRN:bun6jxz) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/lib.rs#L32)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This appears to be a specialized version of:

```
let prepared = original + alignment - 1;
let aligned = prepared - prepared % alignment;
```

However, it requires the `MNL_ALIGNTO` to always be a power of two. It is now (4), but maybe it's a good idea to avoid this requirement in case the value changes in the future? Or maybe just change `MNL_ALIGNTO` to be `1 << 2`,  so its clearer?
</blockquote></details>

I have not defined this myself, so this code is not invented by me. It's just copied from `libmnl` and the syntax translated. I would rather not invent my own arithmetic if possible, but rather use the exact same thing `libmnl` uses.

Only reason I define it myself at all is that bindgen can't generate bindings for C macros.

---

*[mnl/src/callback.rs, line 1 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASQIXW0pD4hClo6vjR:-LASXl4z3-Q5RdeOQWqN:b-tqyh74) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl/src/callback.rs#L1)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I don't understand why `nlmsghdr` is required. `c_int` appears to be unused as well.
</blockquote></details>

True, well spotted. This is something that is brought in in the next PR and I did `git add -p` on this file without being too careful. Yes, they are unused now, but will be used in the next PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by jvff** [comment]
*[mnl-sys/src/bindings.rs, line 56 at r1](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3#-LASTmA4BEpnBdiv2VzB:-LASc8NG4xtN0xui3MD9:bqjbyqs) ([raw file](https://github.com/mullvad/mnl-rs/blob/8d617a8f5370ff96cfd6d063dc15422578fa102f/mnl-sys/src/bindings.rs#L56)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Those types were generated by bindgen. I have not changed any types as generated by bindgen. I personally don't feel that it's very important since they are just typedefs and are guaranteed to be the same size anyway?
</blockquote></details>

Ok, better to stick with the generated types then. Weird that it uses `usize` and `isize` though, from what I understood there's no guarantee in the standards that they map to the same types. But that would be a `bindgen` issue, not something for this crate.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Comment by jvff** [comment]
Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mnl-rs/3)*

**Pull request merged**
